### ISSUE TITLE
add redux flow to show the id of the network

### ISSUE THREAD

**Issue by n1c01a5** [kleros/dapper#18]
https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version

**Comment by epiqueras** [comment]
Implemented here:
https://github.com/kleros/openiico/blob/develop/src/bootstrap/dapp-api.js
https://github.com/kleros/openiico/blob/develop/src/components/chain-hash/index.js

**Comment by n1c01a5** [comment]
👍
