### ISSUE TITLE
remove some `console.log` like redux-saga restart when we run the tests

### ISSUE THREAD

**Issue by n1c01a5** [kleros/dapper#22]
maybe use
```
 if (process.env.NODE_ENV !== 'test') {
    console.log('my log');
}
```

or `jest --silent`

**Comment by epiqueras** [comment]
This is already implemented.

See https://github.com/kleros/dapper/blob/d447cd42cb5d79ed96958b388beb72be2bbb6f0e/src/sagas/index.js#L21-L29
